npx shadcn@latest add card 
npx shadcn@latest add card-content
npx shadcn@latest add card-description
npx shadcn@latest add card-footer
npx shadcn@latest add card-header
npx shadcn@latest add card-title
npx shadcn@latest add input
npx shadcn@latest add label
npx shadcn@latest add select
npx shadcn@latest add select-content
npx shadcn@latest add select-item
npx shadcn@latest add select-trigger
